export enum KernelRuntimeType {
  LOAD_BALANCING = "LOAD_BALANCING",
  EVENT_THROTTLING = "EVENT_THROTTLING",
  EXECUTION_PRIORITIZATION = "EXECUTION_PRIORITIZATION",
  GRAPH_REBALANCING = "GRAPH_REBALANCING",
  GOVERNANCE_SMOOTHING = "GOVERNANCE_SMOOTHING",
  FEEDBACK_CONTROL = "FEEDBACK_CONTROL",
  RESOURCE_OPTIMIZATION = "RESOURCE_OPTIMIZATION"
}
