export enum ExecutionState {
  IDLE = "IDLE",
  CLAIMING_TICKET = "CLAIMING_TICKET",
  CREATING_SESSION = "CREATING_SESSION",
  INITIALIZING = "INITIALIZING",
  EXECUTING = "EXECUTING",
  CHECKPOINT = "CHECKPOINT",
  COMPLETING = "COMPLETING",
  COMPLETED = "COMPLETED",
  FAILED = "FAILED",
  TIMEOUT = "TIMEOUT",
  ROLLBACK = "ROLLBACK",
  ARCHIVED = "ARCHIVED"
}
