export enum AuditTag {
  AUDIT_GENERATION_G5 = "AUDIT-GENERATION:G5",
  AUDIT_SPRINT_X24 = "AUDIT-SPRINT:X-24",
  AUDIT_RUNTIME = "AUDIT-RUNTIME:AdaptiveCoordinationRuntime",
  AUDIT_LAYER_EXECUTIVE = "AUDIT-LAYER:EXECUTIVE",
  AUDIT_DECISION_GENERATED = "AUDIT-DECISION:GENERATED",
  AUDIT_CONSENSUS_PASS = "AUDIT-CONSENSUS:PASS",
  AUDIT_DELEGATION_READY = "AUDIT-DELEGATION:READY"
}

export function createAuditTrace(traceId: string): string {
  return `AUDIT-TRACE:${traceId}`;
}
