export enum CoordinationState {
  IDLE = "IDLE",
  COLLECTING_CONTEXT = "COLLECTING_CONTEXT",
  QUERYING_RUNTIMES = "QUERYING_RUNTIMES",
  CONSENSUS = "CONSENSUS",
  GENERATING_PLAN = "GENERATING_PLAN",
  VALIDATING_PLAN = "VALIDATING_PLAN",
  GENERATING_DECISION = "GENERATING_DECISION",
  VALIDATING_DECISION = "VALIDATING_DECISION",
  GENERATING_DELEGATION = "GENERATING_DELEGATION",
  DELEGATING_EXECUTION = "DELEGATING_EXECUTION",
  COMPLETED = "COMPLETED",
  FAILED = "FAILED",
  ARCHIVED = "ARCHIVED"
}
