export enum CoordinationPolicy {
  FAIL_FAST = "FAIL_FAST",
  CONSENSUS = "CONSENSUS",
  MAJORITY = "MAJORITY",
  PRIORITY_OVERRIDE = "PRIORITY_OVERRIDE",
  EMERGENCY_OVERRIDE = "EMERGENCY_OVERRIDE"
}
