export enum CoordinationTarget {
  SYSTEM_STABILIZATION = "SYSTEM_STABILIZATION",
  PERFORMANCE_BOOST = "PERFORMANCE_BOOST",
  RISK_MITIGATION = "RISK_MITIGATION",
  ROUTINE_EXECUTION = "ROUTINE_EXECUTION"
}
