export enum ResourcePolicy {
  STRICT_LIMIT = "STRICT_LIMIT",
  BURST_ALLOWED = "BURST_ALLOWED",
  PREEMPTION_ALLOWED = "PREEMPTION_ALLOWED",
  EMERGENCY_MODE = "EMERGENCY_MODE",
  COST_SAVING = "COST_SAVING"
}
