export enum ResourceState {
  IDLE = "IDLE",
  COLLECTING_REQUIREMENTS = "COLLECTING_REQUIREMENTS",
  CHECKING_CAPACITY = "CHECKING_CAPACITY",
  CREATING_RESERVATION = "CREATING_RESERVATION",
  VALIDATING_RESERVATION = "VALIDATING_RESERVATION",
  ALLOCATING_RESOURCES = "ALLOCATING_RESOURCES",
  VALIDATING_ALLOCATION = "VALIDATING_ALLOCATION",
  SCHEDULING = "SCHEDULING",
  COMMITTING_RESOURCES = "COMMITTING_RESOURCES",
  READY = "READY",
  COMPLETED = "COMPLETED",
  FAILED = "FAILED",
  ARCHIVED = "ARCHIVED"
}
