export enum KnowledgeType {
    PATTERN = 'PATTERN',
    RULE = 'RULE',
    ARCHITECTURE = 'ARCHITECTURE',
    DECISION = 'DECISION',
    IMPLEMENTATION_PLAN = 'IMPLEMENTATION_PLAN',
    WALKTHROUGH = 'WALKTHROUGH',
    RELEASE_NOTE = 'RELEASE_NOTE',
    EXECUTION_LEDGER = 'EXECUTION_LEDGER',
    PROMPT = 'PROMPT',
    TEMPLATE = 'TEMPLATE',
    BEST_PRACTICE = 'BEST_PRACTICE',
    FAILURE_PATTERN = 'FAILURE_PATTERN',
    CHECKLIST = 'CHECKLIST',
    PLAYBOOK = 'PLAYBOOK',
    RUNBOOK = 'RUNBOOK'
}
