export enum ActivationStage {
  READY = "READY",
  ACTIVATING = "ACTIVATING",
  LINE_VERIFYING = "LINE_VERIFYING",
  GAS_VERIFYING = "GAS_VERIFYING",
  DASHBOARD_VERIFYING = "DASHBOARD_VERIFYING",
  AUDIT_VERIFYING = "AUDIT_VERIFYING",
  ACTIVE = "ACTIVE",
  FAILED = "FAILED"
}
