export enum ValidationSeverity {
  PASS = 'PASS',
  WARNING = 'WARNING',
  MINOR = 'MINOR',
  MAJOR = 'MAJOR',
  CRITICAL = 'CRITICAL'
}

export enum ValidationStatus {
  CREATED = 'CREATED',
  PLANNING = 'PLANNING',
  VALIDATOR_SELECTED = 'VALIDATOR_SELECTED',
  READY = 'READY',
  VALIDATING = 'VALIDATING',
  AGGREGATING = 'AGGREGATING',
  VERIFIED = 'VERIFIED',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  RETRYING = 'RETRYING',
  ARCHIVED = 'ARCHIVED',
  TIMEOUT = 'TIMEOUT',
  CANCELLED = 'CANCELLED'
}

export type ValidationConfidence = number; // 0.0 to 1.0
