export enum StabilizationType {
  FEEDBACK_CONTROL = "FEEDBACK_CONTROL",
  LOOP_DAMPING = "LOOP_DAMPING",
  EVENT_THROTTLING = "EVENT_THROTTLING",
  GRAPH_STABILIZATION = "GRAPH_STABILIZATION",
  KERNEL_BALANCING = "KERNEL_BALANCING",
  GOVERNANCE_NORMALIZATION = "GOVERNANCE_NORMALIZATION",
  EXECUTION_SMOOTHING = "EXECUTION_SMOOTHING"
}
