export enum PolicyState {
  IDLE = "IDLE",
  COLLECTING_CONTEXT = "COLLECTING_CONTEXT",
  EVALUATING_RULES = "EVALUATING_RULES",
  RESOLVING_CONFLICTS = "RESOLVING_CONFLICTS",
  GENERATING_POLICY = "GENERATING_POLICY",
  VALIDATING_POLICY = "VALIDATING_POLICY",
  APPROVING_POLICY = "APPROVING_POLICY",
  READY = "READY",
  ACTIVATING_POLICY = "ACTIVATING_POLICY",
  COMPLETED = "COMPLETED",
  FAILED = "FAILED",
  ARCHIVED = "ARCHIVED"
}
