export enum OrchestrationState {
    CREATED = 'CREATED',
    PLANNING = 'PLANNING',
    SCHEDULING = 'SCHEDULING',
    READY = 'READY',
    DISPATCHING = 'DISPATCHING',
    EXECUTING = 'EXECUTING',
    PAUSED = 'PAUSED',
    RESUMED = 'RESUMED',
    COMPLETED = 'COMPLETED',
    ARCHIVED = 'ARCHIVED',
    FAILED = 'FAILED',
    RETRYING = 'RETRYING',
    CANCELLED = 'CANCELLED'
}
