export enum PolicyProfile {
  STRICT_SAFETY = "STRICT_SAFETY",
  MAX_PERFORMANCE = "MAX_PERFORMANCE",
  COST_OPTIMIZED = "COST_OPTIMIZED",
  BALANCED = "BALANCED",
  EMERGENCY_RECOVERY = "EMERGENCY_RECOVERY"
}
