export enum RoutingState {
  IDLE = "IDLE",
  SENSING = "SENSING",
  EVALUATING_CONTEXT = "EVALUATING_CONTEXT",
  DETERMINING_PATH = "DETERMINING_PATH",
  VALIDATING_PATH = "VALIDATING_PATH",
  READY = "READY",
  ROUTING = "ROUTING",
  COMPLETED = "COMPLETED",
  FAILED = "FAILED",
  ARCHIVED = "ARCHIVED"
}
