export enum RoutingPath {
  FAST_TRACK = "FAST_TRACK",
  STANDARD_PATH = "STANDARD_PATH",
  STRICT_VALIDATION_PATH = "STRICT_VALIDATION_PATH",
  MANUAL_REVIEW_PATH = "MANUAL_REVIEW_PATH",
  THROTTLED_PATH = "THROTTLED_PATH",
  SANDBOX_PATH = "SANDBOX_PATH",
  RECOVERY_PATH = "RECOVERY_PATH",
  BLOCKED = "BLOCKED"
}
