export enum ValidationCapability {
  CAN_PLAN_VALIDATION = 'CAN_PLAN_VALIDATION',
  CAN_SELECT_VALIDATOR = 'CAN_SELECT_VALIDATOR',
  CAN_AGGREGATE_RESULT = 'CAN_AGGREGATE_RESULT',
  CAN_SCORE_VALIDATION = 'CAN_SCORE_VALIDATION',
  CAN_VERIFY_VALIDATION = 'CAN_VERIFY_VALIDATION',
  CAN_RETRY_VALIDATION = 'CAN_RETRY_VALIDATION',
  CAN_CANCEL_VALIDATION = 'CAN_CANCEL_VALIDATION',
  CAN_TIMEOUT_VALIDATION = 'CAN_TIMEOUT_VALIDATION',
  
  // Future extensions (Generation 5+)
  CAN_BUILD_VALIDATION_GRAPH = 'CAN_BUILD_VALIDATION_GRAPH',
  CAN_COLLECT_EVIDENCE = 'CAN_COLLECT_EVIDENCE',
  CAN_GENERATE_SCORE = 'CAN_GENERATE_SCORE',
  CAN_VERIFY_GRAPH = 'CAN_VERIFY_GRAPH',
  CAN_VALIDATE_PIPELINE = 'CAN_VALIDATE_PIPELINE',
  CAN_SELECT_PLUGIN = 'CAN_SELECT_PLUGIN'
}
