export enum KernelAdaptiveStatus {
  IDLE = "IDLE",
  SENSING = "SENSING",
  MAPPING = "MAPPING",
  EVALUATING = "EVALUATING",
  DECIDING = "DECIDING",
  SIMULATING = "SIMULATING",
  ADAPTING = "ADAPTING",
  STABLE = "STABLE"
}
