export interface IChangelogBuilder {
  buildChangelog(repositoryId: string, fromVersion?: string, toVersion?: string): Promise<string>;
}

export class ChangelogBuilder implements IChangelogBuilder {
  public async buildChangelog(repositoryId: string, fromVersion?: string, toVersion?: string): Promise<string> {
    return `# Release ${toVersion}\n\n* Generated by AIOS ChangelogBuilder.`;
  }
}
