export enum AuditTag {
  AUDIT_GENERATION_G5 = "AUDIT-GENERATION:G5",
  AUDIT_SPRINT_X25 = "AUDIT-SPRINT:X-25",
  AUDIT_RUNTIME = "AUDIT-RUNTIME:ResourceManagementRuntime",
  AUDIT_LAYER_RESOURCE = "AUDIT-LAYER:RESOURCE",
  AUDIT_POOL_PASS = "AUDIT-POOL:PASS",
  AUDIT_RESERVATION_PASS = "AUDIT-RESERVATION:PASS",
  AUDIT_QUOTA_PASS = "AUDIT-QUOTA:PASS",
  AUDIT_ALLOCATION_PASS = "AUDIT-ALLOCATION:PASS",
  AUDIT_RESULT_PASS = "AUDIT-RESULT:PASS"
}

export function createAuditTrace(traceId: string): string {
  return `AUDIT-TRACE:${traceId}`;
}
