export type AuditEventType =
  | 'REQUEST_STARTED'
  | 'VALIDATION_COMPLETED'
  | 'ROUTING_COMPLETED'
  | 'HANDLER_COMPLETED'
  | 'REQUEST_COMPLETED'
  | 'REQUEST_FAILED';

export const AuditEvent = {
  REQUEST_STARTED: 'REQUEST_STARTED' as AuditEventType,
  VALIDATION_COMPLETED: 'VALIDATION_COMPLETED' as AuditEventType,
  ROUTING_COMPLETED: 'ROUTING_COMPLETED' as AuditEventType,
  HANDLER_COMPLETED: 'HANDLER_COMPLETED' as AuditEventType,
  REQUEST_COMPLETED: 'REQUEST_COMPLETED' as AuditEventType,
  REQUEST_FAILED: 'REQUEST_FAILED' as AuditEventType,
};
