export enum KernelIntegrationType {
  GOVERNANCE_SYNC = "GOVERNANCE_SYNC",
  EVENT_PROPAGATION = "EVENT_PROPAGATION",
  GRAPH_SYNC = "GRAPH_SYNC",
  EXECUTION_SYNC = "EXECUTION_SYNC",
  PLANNING_SYNC = "PLANNING_SYNC",
  AUDIT_SYNC = "AUDIT_SYNC",
  HEALING_SYNC = "HEALING_SYNC",
  OPTIMIZATION_SYNC = "OPTIMIZATION_SYNC",
  EVOLUTION_SYNC = "EVOLUTION_SYNC"
}
