export enum KernelType {
  GOVERNANCE_REQUEST = "GOVERNANCE_REQUEST",
  POLICY_EVALUATION = "POLICY_EVALUATION",
  META_ROUTING = "META_ROUTING",
  CONSTRAINT_ENFORCEMENT = "CONSTRAINT_ENFORCEMENT",
  ARBITRATION = "ARBITRATION",
  SYSTEM_CONTROL = "SYSTEM_CONTROL"
}
