export enum BootstrapStep {
  VALIDATE = 'VALIDATE',
  CREATE_REPOSITORY = 'CREATE_REPOSITORY',
  GENERATE_TEMPLATE = 'GENERATE_TEMPLATE',
  INITIALIZE_GIT = 'INITIALIZE_GIT',
  INITIAL_COMMIT = 'INITIAL_COMMIT',
  PUSH = 'PUSH',
  CREATE_TAG = 'CREATE_TAG',
  CREATE_RELEASE = 'CREATE_RELEASE',
  COMPLETE = 'COMPLETE',
  FAILED = 'FAILED'
}
