/**
 * Transformation OS Internal Protocol Specification (Canonical Data Dictionary)
 * 
 * WARNING: TYPE FIRST RULE STRICTLY ENFORCED.
 * - This file contains ONLY interface, type, and enum definitions.
 * - NO classes. NO functions. NO default values. NO logic. NO validation.
 * - ZERO external dependencies (no imports allowed).
 */

// ============================================================================
// 1. Value Objects
// ============================================================================
export type TraceId = string;
export type EventId = string;
export type DataRef = string;
export type PolicyRef = string;

// ============================================================================
// 2. Entities
// ============================================================================

/**
 * OSEvent
 * Entity: The immutable fact of state change used globally across the OS.
 * Follows CloudEvents-inspired envelope structure.
 */
export interface OSEvent {
  readonly eventId: EventId;         // UUID generated by Publisher
  readonly traceId: TraceId;         // Global tracing identifier
  readonly source: string;           // URI of the emitter (e.g. 'os://runtime/automation')
  readonly subject: string;          // URI of the target resource (e.g. 'automation-job://xxxx')
  readonly type: string;             // Verb indicating state change (e.g. 'CREATED', 'DISPATCHED')
  readonly schemaVersion: string;    // Schema version (e.g. '1.0')
  readonly occurredAt: string;       // ISO8601 timestamp
  readonly dataRef?: DataRef;        // URI pointing to logs, payloads, or details
}

/**
 * Command
 * Value Object: The specific execution request that the system must fulfill.
 * Includes explicit identification for Replay, Audit, and Versioning.
 */
export interface Command<TPayload = unknown> {
  readonly commandId: string;
  readonly type: string;
  readonly version: string;
  readonly payload: TPayload;
}

/**
 * AutomationJob
 * Entity: The immutable delivery contract sent from Transformation Layer.
 * It serves as the envelope carrying the specific Command to be executed.
 */
export interface AutomationJob {
  readonly jobId: string;            // The delivery slip identifier
  readonly traceId: TraceId;         // Tied to the global trace
  readonly command: Command;         // The business command to execute
  readonly policyRef: PolicyRef;     // URI defining timeout/retry rules
}

// ============================================================================
// 3. Read Models
// ============================================================================

/**
 * AutomationState
 * Read Model: The volatile current state of a delivery, reconstructed from Events.
 */
export interface AutomationState {
  jobId: string;
  currentStatus: string;             // E.g. 'CREATED', 'QUEUED', 'DISPATCHED', 'ACKNOWLEDGED', 'FINISHED', 'EXPIRED', 'DEAD'
  attempt: number;                   // Number of delivery attempts
  workerId?: string;                 // Explicit worker assigned to this delivery
}


