export enum GovernanceEventType {
  KNOWLEDGE_EVENT = "KNOWLEDGE_EVENT",
  POLICY_EVENT = "POLICY_EVENT",
  REVIEW_EVENT = "REVIEW_EVENT",
  SCOPE_EVENT = "SCOPE_EVENT",
  SYSTEM_EVENT = "SYSTEM_EVENT"
}
