export enum LearningSource {
    REASONING_RUNTIME = 'REASONING_RUNTIME',
    KNOWLEDGE_RUNTIME = 'KNOWLEDGE_RUNTIME',
    MEMORY_RUNTIME = 'MEMORY_RUNTIME',
    WORKFLOW_RUNTIME = 'WORKFLOW_RUNTIME',
    DEPLOYMENT_RUNTIME = 'DEPLOYMENT_RUNTIME',
    AI_AGENT_RUNTIME = 'AI_AGENT_RUNTIME',
    REVIEW_RUNTIME = 'REVIEW_RUNTIME',
    NOTIFICATION_RUNTIME = 'NOTIFICATION_RUNTIME',
    DASHBOARD_RUNTIME = 'DASHBOARD_RUNTIME',
    REPOSITORY_RUNTIME = 'REPOSITORY_RUNTIME',
    WORKSPACE_RUNTIME = 'WORKSPACE_RUNTIME',
    PROJECT_RUNTIME = 'PROJECT_RUNTIME',
    RELEASE_RUNTIME = 'RELEASE_RUNTIME'
}
