export enum MemoryType {
    WORKING_MEMORY = 'WORKING_MEMORY',
    CONVERSATION_MEMORY = 'CONVERSATION_MEMORY',
    RUNTIME_MEMORY = 'RUNTIME_MEMORY',
    KNOWLEDGE_CACHE = 'KNOWLEDGE_CACHE',
    SEMANTIC_MEMORY = 'SEMANTIC_MEMORY',
    EPISODE_MEMORY = 'EPISODE_MEMORY',
    REFLECTION_MEMORY = 'REFLECTION_MEMORY'
}
