/**
 * ProjectEventType.ts
 * 
 * Event Types for Project Events
 */

export enum ProjectEventType {
  PROJECT_REGISTERED = 'PROJECT_REGISTERED',
  TASK_ACCEPTED = 'TASK_ACCEPTED',
  WORKFLOW_STARTED = 'WORKFLOW_STARTED',
  WORKFLOW_COMPLETED = 'WORKFLOW_COMPLETED',
  WORKFLOW_FAILED = 'WORKFLOW_FAILED',
  CALLBACK_SENT = 'CALLBACK_SENT'
}
