export enum PredictionTarget {
  LOAD_TREND = "LOAD_TREND",
  EVENT_OCCURRENCE = "EVENT_OCCURRENCE",
  RESOURCE_DEMAND = "RESOURCE_DEMAND",
  ROUTING_BOTTLENECK = "ROUTING_BOTTLENECK",
  GOVERNANCE_PRESSURE = "GOVERNANCE_PRESSURE",
  QUALITY_DEGRADATION = "QUALITY_DEGRADATION",
  TRUST_DRIFT = "TRUST_DRIFT",
  SYSTEM_ENTROPY = "SYSTEM_ENTROPY"
}
