export enum PredictionState {
  IDLE = "IDLE",
  COLLECTING_HISTORY = "COLLECTING_HISTORY",
  AGGREGATING_HISTORY = "AGGREGATING_HISTORY",
  ANALYZING_TRENDS = "ANALYZING_TRENDS",
  GENERATING_PREDICTIONS = "GENERATING_PREDICTIONS",
  VALIDATING_PREDICTIONS = "VALIDATING_PREDICTIONS",
  READY = "READY",
  COMPLETED = "COMPLETED",
  FAILED = "FAILED",
  ARCHIVED = "ARCHIVED"
}
