export enum ReasoningState {
    CREATED = 'CREATED',
    COLLECTING_EVIDENCE = 'COLLECTING_EVIDENCE',
    GENERATING_HYPOTHESIS = 'GENERATING_HYPOTHESIS',
    EVALUATING = 'EVALUATING',
    DECIDED = 'DECIDED',
    VALIDATED = 'VALIDATED',
    ARCHIVED = 'ARCHIVED'
}
