export enum PlanningType {
  SYSTEM = "SYSTEM",
  EXECUTION = "EXECUTION",
  OPTIMIZATION = "OPTIMIZATION",
  REVIEW = "REVIEW",
  GOVERNANCE = "GOVERNANCE",
  EVENT_DRIVEN = "EVENT_DRIVEN",
  API_DRIVEN = "API_DRIVEN"
}
