export enum AutonomousState {
    CREATED = 'CREATED',
    EVALUATING = 'EVALUATING',
    RISK_ANALYZED = 'RISK_ANALYZED',
    PLANNED = 'PLANNED',
    APPROVED = 'APPROVED',
    EXECUTING = 'EXECUTING',
    VALIDATING = 'VALIDATING',
    VERIFIED = 'VERIFIED',
    PROMOTED = 'PROMOTED',
    ROLLING_BACK = 'ROLLING_BACK',
    ARCHIVED = 'ARCHIVED'
}
