export enum AITaskState {
  CREATED = 'CREATED',
  ASSIGNED = 'ASSIGNED',
  RUNNING = 'RUNNING',
  HANDOFF_PENDING = 'HANDOFF_PENDING',
  REASSIGNING = 'REASSIGNING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED'
}
