export enum AuditTag {
  AUDIT_GENERATION_G5 = "AUDIT-GENERATION:G5",
  AUDIT_SPRINT_X26 = "AUDIT-SPRINT:X-26",
  AUDIT_RUNTIME = "AUDIT-RUNTIME:AdaptiveSchedulingRuntime",
  AUDIT_LAYER_SCHEDULING = "AUDIT-LAYER:SCHEDULING",
  AUDIT_QUEUE_PASS = "AUDIT-QUEUE:PASS",
  AUDIT_DISPATCH_PASS = "AUDIT-DISPATCH:PASS",
  AUDIT_TICKET_PASS = "AUDIT-TICKET:PASS",
  AUDIT_PREEMPTION_PASS = "AUDIT-PREEMPTION:PASS",
  AUDIT_RESULT_PASS = "AUDIT-RESULT:PASS"
}

export function createAuditTrace(traceId: string): string {
  return `AUDIT-TRACE:${traceId}`;
}
