export enum TicketState {
  CREATED = "CREATED",
  RESERVED = "RESERVED",
  DISPATCHED = "DISPATCHED",
  CLAIMED = "CLAIMED",
  EXECUTING = "EXECUTING",
  FINISHED = "FINISHED",
  EXPIRED = "EXPIRED",
  CANCELLED = "CANCELLED"
}
