export enum PromotionCapability {
  CAN_ASSESS_PROMOTION = 'CAN_ASSESS_PROMOTION',
  CAN_DETECT_CONFLICT = 'CAN_DETECT_CONFLICT',
  CAN_MERGE_KNOWLEDGE = 'CAN_MERGE_KNOWLEDGE',
  CAN_UPDATE_LINEAGE = 'CAN_UPDATE_LINEAGE',
  CAN_VERSION_KNOWLEDGE = 'CAN_VERSION_KNOWLEDGE',
  CAN_ARCHIVE_PROMOTION = 'CAN_ARCHIVE_PROMOTION',
  CAN_REGISTER_KNOWLEDGE = 'CAN_REGISTER_KNOWLEDGE',
  CAN_GENERATE_VERSION = 'CAN_GENERATE_VERSION',
  CAN_REGISTER_LINEAGE = 'CAN_REGISTER_LINEAGE',
  CAN_COMMIT_PROMOTION = 'CAN_COMMIT_PROMOTION',
  CAN_SIMULATE_MERGE = 'CAN_SIMULATE_MERGE',
  CAN_VALIDATE_PROMOTION = 'CAN_VALIDATE_PROMOTION'
}
