export enum PromotionState {
  CREATED = 'CREATED',
  ASSESSING = 'ASSESSING',
  QUALITY_CHECK = 'QUALITY_CHECK',
  CONFLICT_ANALYSIS = 'CONFLICT_ANALYSIS',
  READY = 'READY',
  VERSIONING = 'VERSIONING',
  PROMOTING = 'PROMOTING',
  PROMOTED = 'PROMOTED',
  REJECTED = 'REJECTED',
  ARCHIVED = 'ARCHIVED'
}

export enum ConflictType {
  VERSION = 'VERSION',
  DUPLICATE = 'DUPLICATE',
  SEMANTIC = 'SEMANTIC',
  POLICY = 'POLICY',
  LINEAGE = 'LINEAGE',
  DOMAIN = 'DOMAIN',
  SIGNATURE = 'SIGNATURE'
}
