export enum AuditGateStatus {
  IDLE = "IDLE",
  EVALUATING = "EVALUATING",
  ANALYZING = "ANALYZING",
  VALIDATING = "VALIDATING",
  BLOCKED = "BLOCKED",
  APPROVED = "APPROVED",
  ESCALATED = "ESCALATED"
}
