import { ValidationResult } from '../models/ValidationResult';
import { ValidationScore } from '../models/ValidationScore';
import { ScoringPolicy } from '../policy/ScoringPolicy';

export class ValidationScoringService {
  constructor(private policy: ScoringPolicy) {}

  public score(result: ValidationResult): ValidationScore {
    // In foundation, we just return the score generated by the mock.
    // In actual implementation, this might validate or compute a score based on raw result metrics.
    return result.score;
  }
}
