export enum GovernanceState {
    CREATED = 'CREATED',
    EVALUATING_POLICY = 'EVALUATING_POLICY',
    ANALYZING_IMPACT = 'ANALYZING_IMPACT',
    VALIDATING_COMPLIANCE = 'VALIDATING_COMPLIANCE',
    DECIDING = 'DECIDING',
    APPROVED = 'APPROVED',
    CONDITION_CHECKED = 'CONDITION_CHECKED',
    REJECTED = 'REJECTED',
    DEFERRED = 'DEFERRED',
    ENFORCING = 'ENFORCING',
    ARCHIVED = 'ARCHIVED'
}
