export enum DevelopmentContextStatus {
  CREATED = 'CREATED',
  INITIALIZED = 'INITIALIZED',
  VALIDATING = 'VALIDATING',
  REVIEWING = 'REVIEWING',
  GOVERNING = 'GOVERNING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
}
