export enum EvolutionType {
  STRUCTURAL = "STRUCTURAL",
  BEHAVIORAL = "BEHAVIORAL",
  PERFORMANCE = "PERFORMANCE",
  GOVERNANCE = "GOVERNANCE",
  ARCHITECTURAL = "ARCHITECTURAL",
  CROSS_LAYER = "CROSS_LAYER"
}
