export enum SafetyStatus {
  IDLE = "IDLE",
  ANALYZING = "ANALYZING",
  SIMULATING = "SIMULATING",
  VALIDATING = "VALIDATING",
  BLOCKED = "BLOCKED",
  APPROVED = "APPROVED",
  ESCALATED = "ESCALATED"
}
