export enum SafetyType {
  STRUCTURAL_REWRITE = "STRUCTURAL_REWRITE",
  BEHAVIORAL_REWRITE = "BEHAVIORAL_REWRITE",
  GRAPH_REWRITE = "GRAPH_REWRITE",
  EXECUTION_REWRITE = "EXECUTION_REWRITE",
  GOVERNANCE_REWRITE = "GOVERNANCE_REWRITE",
  CROSS_LAYER_REWRITE = "CROSS_LAYER_REWRITE"
}
