export enum EvolutionState {
  CREATED = 'CREATED',
  ANALYZING = 'ANALYZING',
  PLANNING = 'PLANNING',
  SIMULATING = 'SIMULATING',
  READY = 'READY',
  APPROVAL = 'APPROVAL',
  APPROVED = 'APPROVED',
  EVOLVING = 'EVOLVING',
  EVOLVED = 'EVOLVED',
  REJECTED = 'REJECTED',
  ARCHIVED = 'ARCHIVED'
}

export enum EvolutionTarget {
  SYSTEM_PROMPT = 'SYSTEM_PROMPT',
  GOVERNANCE_POLICY = 'GOVERNANCE_POLICY',
  WORKFLOW_DEFINITION = 'WORKFLOW_DEFINITION',
  INFERENCE_STRATEGY = 'INFERENCE_STRATEGY',
  KNOWLEDGE_STRUCTURE = 'KNOWLEDGE_STRUCTURE',
  MEMORY_POLICY = 'MEMORY_POLICY',
  REASONING_POLICY = 'REASONING_POLICY',
  TOOL_SELECTION_POLICY = 'TOOL_SELECTION_POLICY',
  RUNTIME_CONFIGURATION = 'RUNTIME_CONFIGURATION',
  QUALITY_RULE = 'QUALITY_RULE',
  OBSERVABILITY_RULE = 'OBSERVABILITY_RULE',
  METRICS_POLICY = 'METRICS_POLICY'
}

export enum EvolutionStrategy {
  INCREMENTAL_PATCH = 'INCREMENTAL_PATCH',
  FULL_REWRITE = 'FULL_REWRITE',
  A_B_TESTING = 'A_B_TESTING',
  CANARY_RELEASE = 'CANARY_RELEASE',
  POLICY_TUNING = 'POLICY_TUNING',
  PARAMETER_OPTIMIZATION = 'PARAMETER_OPTIMIZATION',
  KNOWLEDGE_REORGANIZATION = 'KNOWLEDGE_REORGANIZATION',
  HYBRID_STRATEGY = 'HYBRID_STRATEGY',
  ROLLOUT_STRATEGY = 'ROLLOUT_STRATEGY'
}
