export enum OptimizationType {
  PERFORMANCE = "PERFORMANCE",
  STRUCTURAL = "STRUCTURAL",
  EXECUTION_FLOW = "EXECUTION_FLOW",
  PLANNING_EFFICIENCY = "PLANNING_EFFICIENCY",
  AUDIT_ACCURACY = "AUDIT_ACCURACY",
  HEALING_STABILITY = "HEALING_STABILITY",
  GRAPH_OPTIMIZATION = "GRAPH_OPTIMIZATION",
  CROSS_LAYER_OPTIMIZATION = "CROSS_LAYER_OPTIMIZATION"
}
