export enum KernelOptimizationType {
  LATENCY_OPTIMIZATION = "LATENCY_OPTIMIZATION",
  THROUGHPUT_OPTIMIZATION = "THROUGHPUT_OPTIMIZATION",
  STABILITY_OPTIMIZATION = "STABILITY_OPTIMIZATION",
  RESOURCE_OPTIMIZATION = "RESOURCE_OPTIMIZATION",
  GRAPH_OPTIMIZATION = "GRAPH_OPTIMIZATION",
  EXECUTION_FLOW_OPTIMIZATION = "EXECUTION_FLOW_OPTIMIZATION",
  GOVERNANCE_OPTIMIZATION = "GOVERNANCE_OPTIMIZATION",
  CROSS_LAYER_OPTIMIZATION = "CROSS_LAYER_OPTIMIZATION"
}
