export enum KernelOptimizationStatus {
  IDLE = "IDLE",
  OBSERVING = "OBSERVING",
  EVALUATING = "EVALUATING",
  SIMULATING = "SIMULATING",
  SELECTING = "SELECTING",
  APPLYING_MODEL = "APPLYING_MODEL",
  LEARNING = "LEARNING",
  STABLE = "STABLE"
}
