export enum KernelRuntimeStatus {
  IDLE = "IDLE",
  MONITORING = "MONITORING",
  ANALYZING = "ANALYZING",
  REGULATING = "REGULATING",
  STABILIZING = "STABILIZING",
  OPTIMIZED = "OPTIMIZED",
  OVERLOADED = "OVERLOADED",
  CRITICAL = "CRITICAL"
}
