import { ITemplateProvider, GeneratedFile } from './ITemplateProvider';
import { ProjectBootstrapManifest } from '../ProjectBootstrapManifest';

export class MarkdownTemplateProvider implements ITemplateProvider {
  public async generateTemplates(manifest: ProjectBootstrapManifest): Promise<GeneratedFile[]> {
    return [
      {
        path: 'README.md',
        content: `# ${manifest.projectName}\n\nGenerated by AIOS Bootstrap.`
      },
      {
        path: 'LICENSE',
        content: `License: ${manifest.license}`
      },
      {
        path: 'CHANGELOG.md',
        content: `# Changelog\n\n## [0.1.0] - Initial Release`
      }
    ];
  }
}
