export enum RepositoryState {
  NEW = 'NEW',
  VALIDATED = 'VALIDATED',
  CREATING = 'CREATING',
  CREATED = 'CREATED',
  CONFIGURED = 'CONFIGURED',
  PUSHED = 'PUSHED',
  READY = 'READY',
  ARCHIVED = 'ARCHIVED',
  DELETED = 'DELETED',
  FAILED = 'FAILED'
}
