export enum MetaGovernanceType {
  POLICY_CONTROL = "POLICY_CONTROL",
  RULE_MANAGEMENT = "RULE_MANAGEMENT",
  CONFLICT_RESOLUTION = "CONFLICT_RESOLUTION",
  PERMISSION_CONTROL = "PERMISSION_CONTROL",
  SYSTEM_GOVERNANCE = "SYSTEM_GOVERNANCE",
  CROSS_LAYER_GOVERNANCE = "CROSS_LAYER_GOVERNANCE"
}
