export enum EvolutionCapability {
  CAN_PLAN_EVOLUTION = 'CAN_PLAN_EVOLUTION',
  CAN_SIMULATE_EVOLUTION = 'CAN_SIMULATE_EVOLUTION',
  CAN_APPROVE_EVOLUTION = 'CAN_APPROVE_EVOLUTION',
  CAN_APPLY_EVOLUTION = 'CAN_APPLY_EVOLUTION',
  CAN_REJECT_EVOLUTION = 'CAN_REJECT_EVOLUTION',
  CAN_RECORD_EVOLUTION = 'CAN_RECORD_EVOLUTION',
  CAN_ANALYZE_IMPACT = 'CAN_ANALYZE_IMPACT',
  CAN_ESTIMATE_BENEFIT = 'CAN_ESTIMATE_BENEFIT',
  CAN_SELECT_STRATEGY = 'CAN_SELECT_STRATEGY',
  CAN_GENERATE_SIMULATION = 'CAN_GENERATE_SIMULATION',
  CAN_ESTIMATE_COMPATIBILITY = 'CAN_ESTIMATE_COMPATIBILITY',
  CAN_RECORD_HISTORY = 'CAN_RECORD_HISTORY'
}
