export enum RuntimeCapability {
  CAN_CREATE_REPOSITORY = 'CAN_CREATE_REPOSITORY',
  CAN_RELEASE = 'CAN_RELEASE',
  CAN_DISCOVER = 'CAN_DISCOVER',
  CAN_PLAN = 'CAN_PLAN',
  CAN_DEPLOY = 'CAN_DEPLOY',
  CAN_BUILD = 'CAN_BUILD',
  CAN_TEST = 'CAN_TEST',
  CAN_MANAGE_ISSUES = 'CAN_MANAGE_ISSUES',
  
  // Phase 4 Runtime Capabilities
  VALIDATION = 'VALIDATION',
  CONSOLE = 'CONSOLE',
  PLUGIN = 'PLUGIN',
  MONITORING = 'MONITORING',
  QUALITY = 'QUALITY',
  LEARNING = 'LEARNING',
  AUTOMATION = 'AUTOMATION',
  SECURITY = 'SECURITY',

  // Phase 5 Runtime Capabilities
  OBSERVABILITY = 'OBSERVABILITY',

  // Phase 7 Runtime Capabilities
  GOVERNANCE = 'GOVERNANCE',
  COMPLIANCE = 'COMPLIANCE',

  // Phase 8 Runtime Capabilities
  SANDBOX = 'SANDBOX',

  // Phase 9 Runtime Capabilities
  IDENTITY = 'IDENTITY',
  TRUST = 'TRUST',
  CERTIFICATE = 'CERTIFICATE',

  // Phase 10 Runtime Capabilities
  FEDERATION = 'FEDERATION',
  CROSS_DOMAIN_IDENTITY = 'CROSS_DOMAIN_IDENTITY',
  FEDERATION_TRUST = 'FEDERATION_TRUST'
}
