export enum RuntimeCapability {
  CAN_CREATE_REPOSITORY = 'CAN_CREATE_REPOSITORY',
  CAN_RELEASE = 'CAN_RELEASE',
  CAN_DISCOVER = 'CAN_DISCOVER',
  CAN_PLAN = 'CAN_PLAN',
  CAN_DEPLOY = 'CAN_DEPLOY',
  CAN_BUILD = 'CAN_BUILD',
  CAN_TEST = 'CAN_TEST',
  CAN_MANAGE_ISSUES = 'CAN_MANAGE_ISSUES',
  
  // Phase 4 Runtime Capabilities
  VALIDATION = 'VALIDATION',
  CONSOLE = 'CONSOLE',
  PLUGIN = 'PLUGIN',
  MONITORING = 'MONITORING',
  QUALITY = 'QUALITY',
  LEARNING = 'LEARNING',
  AUTOMATION = 'AUTOMATION',
  SECURITY = 'SECURITY'
}
