export enum RuntimeCapability {
  CAN_CREATE_REPOSITORY = 'CAN_CREATE_REPOSITORY',
  CAN_RELEASE = 'CAN_RELEASE',
  CAN_DISCOVER = 'CAN_DISCOVER',
  CAN_PLAN = 'CAN_PLAN',
  CAN_DEPLOY = 'CAN_DEPLOY',
  CAN_BUILD = 'CAN_BUILD',
  CAN_TEST = 'CAN_TEST',
  CAN_MANAGE_ISSUES = 'CAN_MANAGE_ISSUES',
  
  // Phase 4 Runtime Capabilities
  VALIDATION = 'VALIDATION',
  CONSOLE = 'CONSOLE',
  PLUGIN = 'PLUGIN',
  MONITORING = 'MONITORING',
  QUALITY = 'QUALITY',
  LEARNING = 'LEARNING',
  AUTOMATION = 'AUTOMATION',
  SECURITY = 'SECURITY',

  // Phase 5 Runtime Capabilities
  OBSERVABILITY = 'OBSERVABILITY',

  // Phase 7 Runtime Capabilities
  GOVERNANCE = 'GOVERNANCE',
  COMPLIANCE = 'COMPLIANCE',

  // Phase 8 Runtime Capabilities
  SANDBOX = 'SANDBOX',

  // Phase 9 Runtime Capabilities
  IDENTITY = 'IDENTITY',
  TRUST = 'TRUST',
  CERTIFICATE = 'CERTIFICATE',

  // Phase 10 Runtime Capabilities
  FEDERATION = 'FEDERATION',
  CROSS_DOMAIN_IDENTITY = 'CROSS_DOMAIN_IDENTITY',
  FEDERATION_TRUST = 'FEDERATION_TRUST',

  // Phase 11 Runtime Capabilities
  SERVICE = 'SERVICE',
  MARKETPLACE = 'MARKETPLACE',
  LICENSE = 'LICENSE',
  BILLING = 'BILLING',
  SUBSCRIPTION = 'SUBSCRIPTION',

  // Phase 12 Runtime Capabilities
  WORKFLOW = 'WORKFLOW',
  APPLICATION = 'APPLICATION',
  PROVISIONING = 'PROVISIONING',

  // Phase 13 Runtime Capabilities
  ORCHESTRATION = 'ORCHESTRATION',
  AUTO_SCALING = 'AUTO_SCALING',
  RESOURCE_MANAGEMENT = 'RESOURCE_MANAGEMENT',
  SCHEDULING = 'SCHEDULING',
  RECOVERY = 'RECOVERY',

  // Phase 14 Runtime Capabilities
  CONTAINER = 'CONTAINER',
  SANDBOX_EXECUTION = 'SANDBOX_EXECUTION',
  RESOURCE_ISOLATION = 'RESOURCE_ISOLATION',
  PROCESS_SUPERVISION = 'PROCESS_SUPERVISION',
  SECRET_ISOLATION = 'SECRET_ISOLATION',

  // Phase 15 Runtime Capabilities
  DISTRIBUTED_EXECUTION = 'DISTRIBUTED_EXECUTION',
  FEDERATED_SCHEDULING = 'FEDERATED_SCHEDULING',
  REMOTE_ATTESTATION = 'REMOTE_ATTESTATION',
  EXECUTION_DELEGATION = 'EXECUTION_DELEGATION',
  FAILOVER_MANAGEMENT = 'FAILOVER_MANAGEMENT'
}
