export enum BrowserRuntimeState {
  DISCONNECTED = 'DISCONNECTED',
  CONNECTING = 'CONNECTING',
  CONNECTED = 'CONNECTED',
  HEALTHY = 'HEALTHY',
  DEGRADED = 'DEGRADED',
  SESSION_EXPIRED = 'SESSION_EXPIRED',
  PROFILE_INVALID = 'PROFILE_INVALID',
  ERROR = 'ERROR'
}
