/**
 * RuntimeType.ts
 * 
 * Defines the standard enumeration of Runtime targets within the AIOS Execution Framework.
 * These string literals map directly to DispatchTargets generated by the ExecutionDispatcher.
 */
export type RuntimeType = 
  | 'LEGACY_RUNTIME'
  | 'NATIVE_RUNTIME'
  | 'PLUGIN_RUNTIME'
  | 'SANDBOX_RUNTIME'
  | 'EXTERNAL_RUNTIME';
