import { ExecutionSession, SessionStatus } from '../../../core/execution-session/ExecutionSession';
import { ExecutionSessionManager } from '../../../core/execution-session/ExecutionSessionManager';
import { ExecutionResultFactory } from '../../../core/execution-session/ExecutionResultFactory';
import { ISessionIdProvider } from '../../../core/execution-session/ISessionIdProvider';
import { LauncherExecutionRuntime } from '../../../core/launcher-runtime/LauncherExecutionRuntime';
import { LauncherRuntimeRegistry } from '../../../core/launcher-runtime/LauncherRuntimeRegistry';
import { LauncherResult } from '../../../core/launcher/LauncherResult';

function assert(condition: boolean, message: string) {
  if (!condition) {
    throw new Error(`[Assertion Failure] ${message}`);
  }
}

const sleep = (ms: number) => new Promise((resolve) => setTimeout(resolve, ms));

// Custom mock ID provider
class MockSessionIdProvider implements ISessionIdProvider {
  public generateSessionId(): string {
    return 'session-mock-12345';
  }
}

// ==============================================================================
// Test 1: Session Creation, Activation and Status Transitions
// ==============================================================================
async function testSessionActivationAndMetrics() {
  console.log('[Test 1] Session activation and metrics starting...');
  const runtime = new LauncherExecutionRuntime();
  const registry = new LauncherRuntimeRegistry();
  const idProvider = new MockSessionIdProvider();
  const manager = new ExecutionSessionManager(registry, idProvider);

  const mockAllow: LauncherResult = {
    success: true,
    projectId: 'posting-map',
    mode: 'development',
    decision: 'allow',
    reasons: [],
    errorCodes: [],
    warnings: []
  };

  const proc = await runtime.execute(mockAllow, {
    args: ['-e', 'console.log("line-1"); console.log("line-2");']
  });

  const session = manager.createSession(proc, 'req-abc');

  try {
    assert(session.sessionId === 'session-mock-12345', 'Session ID should be generated by mock provider');
    assert(session.status === 'active', 'Session status should be active after manager creation');
    assert(registry.count() === 1, 'Process should be registered');

    // Wait for process stdout streams to pipe and exit
    await new Promise<void>((resolve) => {
      session.process.onExit(() => resolve());
    });

    await sleep(100);

    // Verify stdout lines metrics collected
    assert(session.metrics.stdoutLines === 2, `Expected 2 stdout lines, got: ${session.metrics.stdoutLines}`);
    assert(session.status === 'completed', `Expected completed status, got: ${session.status}`);
    assert(session.exitCode === 0, 'Expected exit code 0');

    console.log('[Test 1] Session activation and metrics: PASSED');
  } finally {
    await session.stop();
  }
}

// ==============================================================================
// Test 2: Session Failed Exit Code Transitions
// ==============================================================================
async function testSessionFailedTransitions() {
  console.log('[Test 2] Session failed transition starting...');
  const runtime = new LauncherExecutionRuntime();
  const registry = new LauncherRuntimeRegistry();
  const idProvider = new MockSessionIdProvider();
  const manager = new ExecutionSessionManager(registry, idProvider);

  const mockAllow: LauncherResult = {
    success: true,
    projectId: 'posting-map',
    mode: 'development',
    decision: 'allow',
    reasons: [],
    errorCodes: [],
    warnings: []
  };

  // Run process that exits with code 5
  const proc = await runtime.execute(mockAllow, {
    args: ['-e', 'process.exit(5);']
  });

  const session = manager.createSession(proc);

  try {
    await new Promise<void>((resolve) => {
      session.process.onExit(() => resolve());
    });

    await sleep(100);

    assert(session.status === 'failed', `Expected failed status, got: ${session.status}`);
    assert(session.exitCode === 5, `Expected exit code 5, got: ${session.exitCode}`);

    console.log('[Test 2] Session failed transition: PASSED');
  } finally {
    await session.stop();
  }
}

// ==============================================================================
// Test 3: Snapshots and Factory Conversion
// ==============================================================================
async function testSnapshotFactory() {
  console.log('[Test 3] Session snapshot factory starting...');
  const runtime = new LauncherExecutionRuntime();
  const registry = new LauncherRuntimeRegistry();
  const idProvider = new MockSessionIdProvider();
  const manager = new ExecutionSessionManager(registry, idProvider);

  const mockAllow: LauncherResult = {
    success: true,
    projectId: 'posting-map',
    mode: 'development',
    decision: 'allow',
    reasons: [],
    errorCodes: [],
    warnings: []
  };

  const proc = await runtime.execute(mockAllow);
  const session = manager.createSession(proc, 'req-999');

  try {
    // 1. Snapshot running status
    const runningSnapshot = ExecutionResultFactory.createSnapshot(session);
    assert(runningSnapshot.status === 'running', 'Expected running snapshot status');
    assert(runningSnapshot.projectId === 'posting-map', 'Project ID mismatch');
    assert(runningSnapshot.requestId === 'req-999', 'Request ID mismatch');
    assert(runningSnapshot.pid === proc.pid, 'PID mismatch');

    // 2. Snapshot stopped status
    await session.stop();
    const stoppedSnapshot = ExecutionResultFactory.createSnapshot(session);
    assert(stoppedSnapshot.status === 'stopped', 'Expected stopped snapshot status');

    console.log('[Test 3] Session snapshot factory: PASSED');
  } finally {
    await session.stop();
  }
}

// ==============================================================================
// Test 4: Session Manager Termination & Registry Sync
// ==============================================================================
async function testManagerTermination() {
  console.log('[Test 4] Manager termination and registry sync starting...');
  const runtime = new LauncherExecutionRuntime();
  const registry = new LauncherRuntimeRegistry();
  const idProvider = new MockSessionIdProvider();
  const manager = new ExecutionSessionManager(registry, idProvider);

  const mockAllow: LauncherResult = {
    success: true,
    projectId: 'posting-map',
    mode: 'development',
    decision: 'allow',
    reasons: [],
    errorCodes: [],
    warnings: []
  };

  const proc = await runtime.execute(mockAllow);
  const session = manager.createSession(proc);

  try {
    assert(registry.count() === 1, 'Registry should have 1 active process');
    assert(manager.listSessions().length === 1, 'Manager should track 1 session');

    await manager.terminateSession(session.sessionId);
    assert(session.status === 'terminated', `Expected terminated session status, got: ${session.status}`);
    assert(registry.count() === 0, 'Registry should be empty after session termination');

    console.log('[Test 4] Manager termination and registry sync: PASSED');
  } finally {
    await session.stop();
  }
}

// ==============================================================================
// Runner
// ==============================================================================
async function runAllTests() {
  console.log('--- Starting Execution Session Foundation Unit Tests ---');
  await testSessionActivationAndMetrics();
  await testSessionFailedTransitions();
  await testSnapshotFactory();
  await testManagerTermination();
  console.log('--- All Execution Session Foundation Unit Tests PASSED ---');
}

runAllTests().catch((err) => {
  console.error('[Test Suite Error]', err);
  process.exit(1);
});
