export enum KernelAdaptiveType {
  STRUCTURAL_ADAPTATION = "STRUCTURAL_ADAPTATION",
  LOAD_ADAPTATION = "LOAD_ADAPTATION",
  GRAPH_RECONFIGURATION = "GRAPH_RECONFIGURATION",
  EXECUTION_FLOW_ADAPTATION = "EXECUTION_FLOW_ADAPTATION",
  GOVERNANCE_ADAPTATION = "GOVERNANCE_ADAPTATION",
  EVENT_TOPOLOGY_ADAPTATION = "EVENT_TOPOLOGY_ADAPTATION",
  CROSS_LAYER_ADAPTATION = "CROSS_LAYER_ADAPTATION"
}
