export enum SchedulingState {
  IDLE = "IDLE",
  ENQUEUING = "ENQUEUING",
  RESOLVING_DEPENDENCIES = "RESOLVING_DEPENDENCIES",
  CHECKING_CONSTRAINTS = "CHECKING_CONSTRAINTS",
  PRIORITIZING = "PRIORITIZING",
  ALLOCATING_TICKET = "ALLOCATING_TICKET",
  DISPATCHING = "DISPATCHING",
  WAITING_EXECUTION = "WAITING_EXECUTION",
  PREEMPTED = "PREEMPTED",
  COMPLETED = "COMPLETED",
  FAILED = "FAILED",
  ARCHIVED = "ARCHIVED"
}
