export enum ScheduleStrategy {
  FIFO = "FIFO",
  ROUND_ROBIN = "ROUND_ROBIN",
  PRIORITY_BASED = "PRIORITY_BASED",
  DEADLINE_DRIVEN = "DEADLINE_DRIVEN",
  PREEMPTIVE_PRIORITY = "PREEMPTIVE_PRIORITY"
}
