export enum BrowserTaskState {
  QUEUED = 'QUEUED',
  WAITING_FOR_LOCK = 'WAITING_FOR_LOCK',
  WAITING_HUMAN_AUTH = 'WAITING_HUMAN_AUTH',
  RUNNING = 'RUNNING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
  TIMEOUT = 'TIMEOUT'
}
