export enum ProvisioningStage {
  REQUESTED = 'REQUESTED',
  PREPARING = 'PREPARING',
  CLONING_TEMPLATE = 'CLONING_TEMPLATE',
  CREATING_STORAGE = 'CREATING_STORAGE',
  REGISTERING_ASSETS = 'REGISTERING_ASSETS',
  VERIFYING = 'VERIFYING',
  READY = 'READY',
  FAILED = 'FAILED'
}
