export enum AuditType {
  SYSTEM_AUDIT = "SYSTEM_AUDIT",
  GOVERNANCE_AUDIT = "GOVERNANCE_AUDIT",
  EXECUTION_AUDIT = "EXECUTION_AUDIT",
  EVENT_AUDIT = "EVENT_AUDIT",
  GRAPH_AUDIT = "GRAPH_AUDIT",
  API_SCHEMA_AUDIT = "API_SCHEMA_AUDIT",
  PLANNING_AUDIT = "PLANNING_AUDIT",
  CROSS_LAYER_AUDIT = "CROSS_LAYER_AUDIT"
}
