export enum ReviewerCapability {
  ARCHITECTURE = 'ARCHITECTURE',
  PERFORMANCE = 'PERFORMANCE',
  SECURITY = 'SECURITY',
  REPOSITORY = 'REPOSITORY',
  API = 'API',
  UI = 'UI',
  DOCUMENTATION = 'DOCUMENTATION',
  GOVERNANCE = 'GOVERNANCE',
}
