export enum StabilizationStatus {
  IDLE = "IDLE",
  MONITORING = "MONITORING",
  ANALYZING = "ANALYZING",
  CORRECTING = "CORRECTING",
  STABILIZING = "STABILIZING",
  STABLE = "STABLE",
  DEGRADED = "DEGRADED"
}
