export enum ReleaseState {
  NEW = 'NEW',
  VALIDATED = 'VALIDATED',
  BUILDING = 'BUILDING',
  PACKAGING = 'PACKAGING',
  TAGGED = 'TAGGED',
  PUBLISHED = 'PUBLISHED',
  FAILED = 'FAILED',
  ARCHIVED = 'ARCHIVED'
}
