export enum AuditTag {
  AUDIT_GENERATION_G5 = "AUDIT-GENERATION:G5",
  AUDIT_SPRINT_X27 = "AUDIT-SPRINT:X-27",
  AUDIT_RUNTIME = "AUDIT-RUNTIME:ExecutionRuntime",
  AUDIT_LAYER_EXECUTION = "AUDIT-LAYER:EXECUTION",
  AUDIT_SESSION_PASS = "AUDIT-SESSION:PASS",
  AUDIT_CHECKPOINT_PASS = "AUDIT-CHECKPOINT:PASS",
  AUDIT_ROLLBACK_PASS = "AUDIT-ROLLBACK:PASS",
  AUDIT_TICKET_PASS = "AUDIT-TICKET:PASS",
  AUDIT_RESULT_PASS = "AUDIT-RESULT:PASS"
}

export function createAuditTrace(traceId: string): string {
  return `AUDIT-TRACE:${traceId}`;
}
