export enum SessionState {
  CREATED = "CREATED",
  CLAIMED = "CLAIMED",
  INITIALIZED = "INITIALIZED",
  RUNNING = "RUNNING",
  ROLLBACK = "ROLLBACK",
  FINISHED = "FINISHED",
  CANCELLED = "CANCELLED"
}
