export enum ReleaseLedgerEntryType {
  RELEASE_STARTED = 'RELEASE_STARTED',
  VERSION_RESOLVED = 'VERSION_RESOLVED',
  CHANGELOG_GENERATED = 'CHANGELOG_GENERATED',
  TAG_CREATED = 'TAG_CREATED',
  RELEASE_CREATED = 'RELEASE_CREATED',
  ASSET_UPLOADED = 'ASSET_UPLOADED',
  PUBLISHED = 'PUBLISHED',
  FAILED = 'FAILED'
}
