export enum PlatformStage {
  INITIALIZING = 'INITIALIZING',
  HARDENING = 'HARDENING',
  AUTHENTICATION = 'AUTHENTICATION',
  AUTHORIZATION = 'AUTHORIZATION',
  LICENSING = 'LICENSING',
  FEATURE_ACCESS = 'FEATURE_ACCESS',
  AIOS_BRIDGE = 'AIOS_BRIDGE',
  VALIDATION = 'VALIDATION',
  ROUTING = 'ROUTING',
  HANDLER = 'HANDLER',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED'
}
