export enum DevelopmentPluginStatus {
  UNLOADED = 'UNLOADED',
  DISCOVERED = 'DISCOVERED',
  LOADED = 'LOADED',
  INITIALIZED = 'INITIALIZED',
  READY = 'READY',
  RUNNING = 'RUNNING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  DISPOSED = 'DISPOSED',
}
