export enum OptimizationState {
  IDLE = "IDLE",
  SENSING = "SENSING",
  ANALYZING = "ANALYZING",
  EVALUATING = "EVALUATING",
  SIMULATING = "SIMULATING",
  DECIDING = "DECIDING",
  READY = "READY",
  COMPLETED = "COMPLETED",
  FAILED = "FAILED",
  ARCHIVED = "ARCHIVED"
}
