export enum HealingType {
  GRAPH_FIX = "GRAPH_FIX",
  EXECUTION_FIX = "EXECUTION_FIX",
  PLAN_CORRECTION = "PLAN_CORRECTION",
  EVENT_RECOVERY = "EVENT_RECOVERY",
  GOVERNANCE_ALIGNMENT = "GOVERNANCE_ALIGNMENT",
  API_SCHEMA_REPAIR = "API_SCHEMA_REPAIR",
  CROSS_LAYER_RECOVERY = "CROSS_LAYER_RECOVERY"
}
