export enum AuditGateType {
  OPTIMIZATION_AUDIT = "OPTIMIZATION_AUDIT",
  ADAPTATION_AUDIT = "ADAPTATION_AUDIT",
  REWRITE_AUDIT = "REWRITE_AUDIT",
  EXECUTION_AUDIT = "EXECUTION_AUDIT",
  GRAPH_AUDIT = "GRAPH_AUDIT",
  GOVERNANCE_AUDIT = "GOVERNANCE_AUDIT",
  CROSS_LAYER_AUDIT = "CROSS_LAYER_AUDIT"
}
